### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by jaydlowrider** [simmel/rabbitmq-auth-backend-kerberos#5]
Hello, 

Doing a compile throws and exception:
{code}

ERL_LIBS=./build/dep-apps erlc -Wall +debug_info -I ./include -pa ebin -o ebin  src/rabbit_auth_backend_kerberos.erl
src/rabbit_auth_backend_kerberos.erl:63: field auth_backend undefined in record user
src/rabbit_auth_backend_kerberos.erl:64: field impl undefined in record user
src/rabbit_auth_backend_kerberos.erl:27: Warning: behaviour rabbit_auth_backend undefined
make: *** [ebin/rabbit_auth_backend_kerberos.beam] Error 1

{code}

Is this still supported? can you please help me. 

Thanks,
Melvin

**Comment by simmel** [comment]
Interesting! Something must have changed recently in RabbitMQ but I
can't find any news about it.

I'll look into it!

**Comment by simmel** [comment]
Seems like the API changed in 3.5, so current code will still work in 3.4.x.

See rabbitmq/rabbitmq-auth-backend-http#8 and rabbitmq/rabbitmq-auth-backend-http@fe9401c

**Comment by simmel** [comment]
haha, I just noticed that you reported the issue linked above too @jaydlowrider ! = )

**Comment by jaydlowrider** [comment]
Lol, Yeah, I was testing out these types of authentication. I got that compiled however. 
Thanks for your help. I was also learning how this will work for kerberos server, I've used docker to host my kerberos server. 

I'm currently testing this if it will work on what we need, I will raise more bugs if I found more things. :)

**Comment by simmel** [comment]
On Sat, 2015-07-04 at 19:18:42 -0700, jaydlowrider wrote:
> Lol, Yeah, I was testing out these types of authentication. I got that compiled however. 

Cool! I ran into other issues with the NIF not being loaded. I'll get
back to you when I get that sorted, I need help from the mailinglist.

> I'm currently testing this if it will work on what we need, I will raise more bugs if I found more things. :)

Cool, do that! I'm going to update the plugin for version >3.5 of
RabbitMQ.

**Comment by jaydlowrider** [comment]
Ok I think I have some questions, however before that, let me give an overview what I am trying to do.

Here is the basic architecture of what we are trying to do...

Client App <==> RabbitMQ <==> ServerApp
(OS SSO) 

I was able to run a simple Kerberos Server using docker. Which is really easy https://github.com/tillt/docker-kdc

And then I've downloaded and compiled your plugin, however I'm kind of confused about your implementation.

As I understood how Kerberos works is documented here:
https://directory.apache.org/apacheds/kerberos-ug/1.1.4-kdc.html

However, when I tested the plugin, I expected that the plugin will pull the information on (Keytab) from the given /etc/krb5.conf file with that I will authenticated, as the keytab contains information of user, or if not, I was expecting that it will load the ticket as it was already been issued, I just don't understand how your plugin works, and *why does it require a password?*

This is what I see if the password is not provided, or if I gave wrong password.

```
=ERROR REPORT==== 5-Jul-2015::12:02:24 ===
closing AMQP connection <0.1842.0> (127.0.0.1:45012 -> 127.0.0.1:5672):
{handshake_error,starting,0,
                 {amqp_error,access_refused,
                             "PLAIN login refused: rabbit_auth_backend_kerberos failed authenticating test@N.FRITZ.BOX: \"krb5_get_init_creds_password: (-1765328161) Already tried ENC-TS-info, looping\"\n",
                             'connection.start_ok'}}
```

if I provide the correct password, I get

```
=INFO REPORT==== 5-Jul-2015::12:02:05 ===
accepting AMQP connection <0.1834.0> (127.0.0.1:45009 -> 127.0.0.1:5672)
```

*Does your plugin worked together with auth-backend-http?* https://github.com/rabbitmq/rabbitmq-auth-backend-http? Because I noticed its using the internal database of users and configurations.

Can you please advice?

Thanks,
Melvin

**Comment by simmel** [comment]
On Sun, 2015-07-05 at 21:06:43 -0700, jaydlowrider wrote:
> However, when I tested the plugin, I expected that the plugin will
> pull the information on (Keytab) from the given /etc/krb5.conf file
> with that I will authenticated, as the keytab contains information of
> user, or if not, I was expecting that it will load the ticket as it
> was already been issued, I just don't understand how your plugin
> works, and *why does it require a password?*

There are two (main ones, atleast) ways to use Kerberos:
* Either you use it to verify passwords centrally (this is typically
refered to as "Kerberos Authentication") which is sort of step 1 in that
picture where your RabbitMQ server is the "User".
OR
* you use your ticket to authenticate via GSSAPI, steps 3-6.

This module only supports Kerberos Authentication and that's why you
need a password.

Ideally you want to use GSSAPI always since then you never give away
your password to a third party. But, to use GSSAPI every service (both
on the client and server side) needs to support GSSAPI. RabbitMQ does
not support it and neither does any AMQP library that I know of.

So to be able to use centralized accounts I implemented this module so
we can atleast take advantage of Kerberos and not have to have
(duplicate) accounts in RabbitMQ.

> This is what I see if the password is not provided, or if I gave wrong password.
> 
> ```
> =ERROR REPORT==== 5-Jul-2015::12:02:24 ===
> closing AMQP connection <0.1842.0> (127.0.0.1:45012 -> 127.0.0.1:5672):
> {handshake_error,starting,0,
>                  {amqp_error,access_refused,
>                              "PLAIN login refused: rabbit_auth_backend_kerberos failed authenticating test@N.FRITZ.BOX: \"krb5_get_init_creds_password: (-1765328161) Already tried ENC-TS-info, looping\"\n",
>                              'connection.start_ok'}}
> ```
> 
> if I provide the correct password, I get
> 
> ```
> =INFO REPORT==== 5-Jul-2015::12:02:05 ===
> accepting AMQP connection <0.1834.0> (127.0.0.1:45009 -> 127.0.0.1:5672)
> ```

That looks exactly like what's supposed to happen. Congratulations!

> *Does your plugin worked together with auth-backend-http?* https://github.com/rabbitmq/rabbitmq-auth-backend-http? Because I noticed its using the internal database of users and configurations.

Yes, it should! I only use the internal database and an easy example.
I've done some updates to the code, but not yet pushed them, which fixes
compatibility with RabbitMQ >=3.5 and takes advantage of the new syntax
and the possibility of using one authentication- and one authorization
plugin.

I will update the code and docs this week for >3.5.
