### ISSUE TITLE
Please mention explicitly that passwords go over the wire

### ISSUE THREAD

**Issue by frozencemetery** [simmel/rabbitmq-auth-backend-kerberos#6]
Hello, I'm glad to hear other people are interested in having Kerberos auth for Rabbit.  However, typically when this is done, the client and server have a Kerberos exchange.  This avoids sending passwords over the wire.

I understand you prefer this model since it doesn't require modifying any client libraries, and there's definitely a use case for it, so I'm not suggesting you change any behavior you don't want to.  But it is the expectation of most people that when a library says "Kerberos auth" on it, passwords are not reaching the rabbit server.

Thanks!

**Comment by simmel** [comment]
On Thu, 2016-09-15 at 10:35:24 -0700, Robbie Harwood wrote:
> Hello, I'm glad to hear other people are interested in having Kerberos
> auth for Rabbit.  However, typically when this is done, the client and
> server have a Kerberos exchange.  This avoids sending passwords over
> the wire.

AFAIK, there are (at least) two ways to use Kerberos. One way is to use,
what I've been learned to call, Kerberos authentication. With it you
supply user/password to a service which in turn uses them to
authenticate you with an KDC.

The other, more prefered security and usability wise, is GSSAPI
authentication. For this you login to your machine or do kinit, retrieve
your tickets and then use them to acquire principals from other services
and authenticate with them.

> I understand you prefer this model since it doesn't require modifying
> any client libraries, and there's definitely a use case for it, so I'm
> not suggesting you change any behavior you don't want to.

Exactly, it's a bit over whelming to add GSSAPI to every client lib out
there = )

I've since learned that Apache QPid supports GSSAPI over AMQP but I
haven't tried it.

> But it is the expectation of most people that when a library says
> "Kerberos auth" on it, passwords are not reaching the rabbit server.

As per my explaination above, that's not what I think or most people
I've ever talked about Kerberos to.

Do you have a suggestion for clarification?

**Comment by frozencemetery** [comment]
Simon Lundström <notifications@github.com> writes:

> Do you have a suggestion for clarification?

How about something like this ("Overview" section in README.md):

This plugin allows your RabbitMQ server authenticate users against a
Kerberos KDC using the password sent to the RabbitMQ server as part of
normal connection.

(You could even add something in here about how this doesn't require any
changes to existing Rabbit clients.)

**Comment by simmel** [comment]
Thanks Robbie!
